############################################################
# +------------------------------------------------------+ #
# |                   CRP v0.0.1                         | #
# +------------------------------------------------------+ #
############################################################

# CRP spreadsheet
# after using crp command this value will be returned
# spreadsheet: https://michalmaniak.tech
spreadsheet: https://michalmaniak.tech

# Defines minimal roll value
# Roll wont be smaller than this value
min-roll: 1
# Defines maximal roll value
# Check overflow value (line 20) for additional options
max-roll: 20

# Defines maximal skill level
# Minimal skill level is set to 0
max-skill: 7

# Should roll value exceed max-roll?
# ex. If user has skill level 7, min-roll 1 and max-roll 20 should roll range looks like <8, 27> (true) or <8, 20> (false)?
overflow: true