name: CRP
version: 0.0.1
author: michalmaniak
main: tech.michalmaniak.CRPlugin
api-version: 1.16
commands:
  crp:
    description: CRP spreadsheet
    usage: /crp
    permission: crp.commands.crp
  skills:
    description: User skills
    usage: /skills
    permission: crp.commands.skills
