name: CRP
version: 0.2.0
author: michalmaniak
website: https://github.com/michalzielinski913
main: tech.michalmaniak.CRPlugin
api-version: 1.16
softdepend: [PlaceholderAPI]
commands:
  crp:
    description: CRP spreadsheet
    usage: /crp
    permission: crp.commands.user.crp
  skills:
    description: User skills
    usage: /skills
    permission: crp.commands.user.skills
  croll:
    description: Combat roll
    usage: /croll
    permission: crp.commands.user.croll
  droll:
    description: Dodge roll
    usage: /droll
    permission: crp.commands.user.droll
  sroll:
    description: Shooring roll
    usage: /sroll
    permission: crp.commands.user.sroll
  mroll:
    description: Magic roll
    usage: /mroll
    permission: crp.commands.user.mroll
  skill:
    description: Skill manipulator command
    usage: /skill <modify> [nick] <Combat, Dodge, Shooting, magic> [value]
    permission: crp.commands.mod.skill