name: CRP
version: 0.0.1
author: michalmaniak
main: tech.michalmaniak.CRPlugin
api-version: 1.16
commands:
  crp:
    description: CRP spreadsheet
    usage: /crp
    permission: crp.commands.crp
  skills:
    description: User skills
    usage: /skills
    permission: crp.commands.skills
  croll:
    description: Combat roll
    usage: /croll
    permission: crp.commands.croll
  droll:
    description: Dodge roll
    usage: /droll
    permission: crp.commands.droll
  sroll:
    description: Shooring roll
    usage: /sroll
    permission: crp.commands.sroll
  mroll:
    description: Magic roll
    usage: /mroll
    permission: crp.commands.mroll